// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: VoltSet

#ifndef _VOLTSET_UI_H
#define _VOLTSET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_StartupScreen.h"
#include "ui_MainScreen.h"
#include "ui_SettingsScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * Confirm_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Zeroing_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logopng_png);    // assets/LogoPNG.png

// FONTS
LV_FONT_DECLARE(ui_font_Archimoto_EXTRA);
LV_FONT_DECLARE(ui_font_Archimoto_Labels);
LV_FONT_DECLARE(ui_font_Archimoto_Numbers);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
