// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: VoltSet

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void StartupDataRetrieval();
void StartupLoadValues(lv_event_t * e);
void MainLoadValues(lv_event_t * e);
void SoftSetValue(lv_event_t * e);
void SoftSaveValue(lv_event_t * e);
void SaveCurrentValues();
void MediumSetValue(lv_event_t * e);
void MediumSaveValue(lv_event_t * e);
void HardSetValue(lv_event_t * e);
void HardSaveValue(lv_event_t * e);
void CustomSetValue(lv_event_t * e);
void CustomSaveValue(lv_event_t * e);
void SettingsLoadValues(lv_event_t * e);
void SaveSetupValue(lv_event_t * e);
void ZeroPedal();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
