// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: VoltSet

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_PresetsButtonContainer;
extern void ui_event_SoftBtn(lv_event_t * e);
extern lv_obj_t * ui_SoftBtn;
extern lv_obj_t * ui_SoftLabel;
extern void ui_event_MediumBtn(lv_event_t * e);
extern lv_obj_t * ui_MediumBtn;
extern lv_obj_t * ui_MediumLabel;
extern void ui_event_HardBtn(lv_event_t * e);
extern lv_obj_t * ui_HardBtn;
extern lv_obj_t * ui_HardLabel;
extern void ui_event_CustomBtn(lv_event_t * e);
extern lv_obj_t * ui_CustomBtn;
extern lv_obj_t * ui_CustomLabel;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_PedalLabel;
extern lv_obj_t * ui_PedalBar;
extern void ui_event_SettingsButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsButton;
extern lv_obj_t * ui_SettingsButtonLabel;
extern lv_obj_t * ui_FrequencyContainer;
extern void ui_event_FrequencyButton(lv_event_t * e);
extern lv_obj_t * ui_FrequencyButton;
extern lv_obj_t * ui_FrequencyTitle;
extern void ui_event_FrequencySlider(lv_event_t * e);
extern lv_obj_t * ui_FrequencySlider;
extern lv_obj_t * ui_FrequencyLabel;
extern lv_obj_t * ui_PowerContainer;
extern void ui_event_PowerButton(lv_event_t * e);
extern lv_obj_t * ui_PowerButton;
extern lv_obj_t * ui_PowerTitle;
extern void ui_event_PowerSlider(lv_event_t * e);
extern lv_obj_t * ui_PowerSlider;
extern lv_obj_t * ui_PowerLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

