// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: VoltSet

#include "ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_PresetsButtonContainer = NULL;
lv_obj_t * ui_SoftBtn = NULL;
lv_obj_t * ui_SoftLabel = NULL;
lv_obj_t * ui_MediumBtn = NULL;
lv_obj_t * ui_MediumLabel = NULL;
lv_obj_t * ui_HardBtn = NULL;
lv_obj_t * ui_HardLabel = NULL;
lv_obj_t * ui_CustomBtn = NULL;
lv_obj_t * ui_CustomLabel = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_PedalLabel = NULL;
lv_obj_t * ui_PedalBar = NULL;
lv_obj_t * ui_SettingsButton = NULL;
lv_obj_t * ui_SettingsButtonLabel = NULL;
lv_obj_t * ui_FrequencyContainer = NULL;
lv_obj_t * ui_FrequencyButton = NULL;
lv_obj_t * ui_FrequencyTitle = NULL;
lv_obj_t * ui_FrequencySlider = NULL;
lv_obj_t * ui_FrequencyLabel = NULL;
lv_obj_t * ui_PowerContainer = NULL;
lv_obj_t * ui_PowerButton = NULL;
lv_obj_t * ui_PowerTitle = NULL;
lv_obj_t * ui_PowerSlider = NULL;
lv_obj_t * ui_PowerLabel = NULL;
// event funtions
void ui_event_MainScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        MainLoadValues(e);
    }
}

void ui_event_SoftBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_HardBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_SoftBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_MediumBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_CustomBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        SoftSetValue(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        SoftSaveValue(e);
        SaveCurrentValues(e);
        Confirm_Animation(ui_SoftBtn, 0);
    }
}

void ui_event_MediumBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_CustomBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_HardBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_SoftBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_MediumBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        MediumSetValue(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        MediumSaveValue(e);
        SaveCurrentValues(e);
        Confirm_Animation(ui_MediumBtn, 0);
    }
}

void ui_event_HardBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_CustomBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_HardBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_MediumBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_SoftBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        HardSetValue(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        HardSaveValue(e);
        SaveCurrentValues(e);
        Confirm_Animation(ui_HardBtn, 0);
    }
}

void ui_event_CustomBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_CustomBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_HardBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_MediumBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_SoftBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        CustomSetValue(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        CustomSaveValue(e);
        SaveCurrentValues(e);
        Confirm_Animation(ui_CustomBtn, 0);
    }
}

void ui_event_SettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_OVER_LEFT, 300, 100, &ui_SettingsScreen_screen_init);
    }
}

void ui_event_FrequencyButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_FrequencyButton, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_PowerButton, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        SaveCurrentValues(e);
    }
}

void ui_event_FrequencySlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_FrequencyLabel, target, "", "");
        _ui_state_modify(ui_CustomBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_HardBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_MediumBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_SoftBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        SaveCurrentValues(e);
    }
}

void ui_event_PowerButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_state_modify(ui_PowerButton, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_FrequencyButton, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        SaveCurrentValues(e);
    }
}

void ui_event_PowerSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_PowerLabel, target, "", "");
        _ui_state_modify(ui_CustomBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_SoftBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_MediumBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_HardBtn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        SaveCurrentValues(e);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetsButtonContainer = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_PresetsButtonContainer);
    lv_obj_set_height(ui_PresetsButtonContainer, 150);
    lv_obj_set_width(ui_PresetsButtonContainer, lv_pct(100));
    lv_obj_set_x(ui_PresetsButtonContainer, 0);
    lv_obj_set_y(ui_PresetsButtonContainer, 91);
    lv_obj_set_align(ui_PresetsButtonContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PresetsButtonContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PresetsButtonContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PresetsButtonContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PresetsButtonContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PresetsButtonContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PresetsButtonContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PresetsButtonContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PresetsButtonContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PresetsButtonContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PresetsButtonContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetsButtonContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetsButtonContainer, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoftBtn = lv_btn_create(ui_PresetsButtonContainer);
    lv_obj_set_width(ui_SoftBtn, lv_pct(45));
    lv_obj_set_height(ui_SoftBtn, lv_pct(40));
    lv_obj_set_align(ui_SoftBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SoftBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SoftBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SoftBtn, lv_color_hex(0x005297), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SoftBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_SoftBtn, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_SoftBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_SoftBtn, 12, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_SoftBtn, 8, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_SoftLabel = lv_label_create(ui_SoftBtn);
    lv_obj_set_width(ui_SoftLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoftLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SoftLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SoftLabel, "SOFT");
    lv_obj_set_style_text_font(ui_SoftLabel, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MediumBtn = lv_btn_create(ui_PresetsButtonContainer);
    lv_obj_set_width(ui_MediumBtn, lv_pct(45));
    lv_obj_set_height(ui_MediumBtn, lv_pct(40));
    lv_obj_set_align(ui_MediumBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MediumBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MediumBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_MediumBtn, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MediumBtn, lv_color_hex(0x005297), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MediumBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_MediumBtn, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_MediumBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_MediumBtn, 12, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_MediumBtn, 8, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_font(ui_MediumBtn, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_MediumLabel = lv_label_create(ui_MediumBtn);
    lv_obj_set_width(ui_MediumLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MediumLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MediumLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MediumLabel, "MEDIUM");
    lv_obj_set_style_text_font(ui_MediumLabel, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HardBtn = lv_btn_create(ui_PresetsButtonContainer);
    lv_obj_set_width(ui_HardBtn, lv_pct(45));
    lv_obj_set_height(ui_HardBtn, lv_pct(40));
    lv_obj_set_x(ui_HardBtn, -94);
    lv_obj_set_y(ui_HardBtn, 40);
    lv_obj_set_align(ui_HardBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HardBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_HardBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HardBtn, lv_color_hex(0x005297), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_HardBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_HardBtn, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_HardBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_HardBtn, 12, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_HardBtn, 8, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_HardLabel = lv_label_create(ui_HardBtn);
    lv_obj_set_width(ui_HardLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HardLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HardLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HardLabel, "HARD");
    lv_obj_set_style_text_font(ui_HardLabel, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CustomBtn = lv_btn_create(ui_PresetsButtonContainer);
    lv_obj_set_width(ui_CustomBtn, lv_pct(45));
    lv_obj_set_height(ui_CustomBtn, lv_pct(40));
    lv_obj_set_align(ui_CustomBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CustomBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CustomBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CustomBtn, lv_color_hex(0x005297), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_CustomBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_CustomBtn, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_CustomBtn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_CustomBtn, 12, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_CustomBtn, 8, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_CustomBtn, lv_color_hex(0x0365B7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_CustomBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_CustomLabel = lv_label_create(ui_CustomBtn);
    lv_obj_set_width(ui_CustomLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CustomLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CustomLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CustomLabel, "Custom");
    lv_obj_set_style_text_font(ui_CustomLabel, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 179);
    lv_obj_set_height(ui_Container4, 52);
    lv_obj_set_x(ui_Container4, -78);
    lv_obj_set_y(ui_Container4, 208);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PedalLabel = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_PedalLabel, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_PedalLabel, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_PedalLabel, -50);
    lv_obj_set_y(ui_PedalLabel, 188);
    lv_obj_set_align(ui_PedalLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PedalLabel, "PEDAL ");
    lv_obj_set_style_text_color(ui_PedalLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PedalLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PedalLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PedalLabel, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PedalBar = lv_bar_create(ui_Container4);
    lv_bar_set_value(ui_PedalBar, 65, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_PedalBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_PedalBar, lv_pct(80));
    lv_obj_set_height(ui_PedalBar, lv_pct(35));
    lv_obj_set_y(ui_PedalBar, 134);
    lv_obj_set_x(ui_PedalBar, lv_pct(14));
    lv_obj_set_align(ui_PedalBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PedalBar, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_radius(ui_PedalBar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PedalBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PedalBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PedalBar, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PedalBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PedalBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PedalBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PedalBar, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PedalBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_PedalBar, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PedalBar, lv_color_hex(0x0F4471), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PedalBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PedalBar, lv_color_hex(0x2095F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PedalBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PedalBar, 100, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PedalBar, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PedalBar, lv_color_hex(0x42FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PedalBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PedalBar, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SettingsButton = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_SettingsButton, 133);
    lv_obj_set_height(ui_SettingsButton, 49);
    lv_obj_set_x(ui_SettingsButton, 87);
    lv_obj_set_y(ui_SettingsButton, 207);
    lv_obj_set_align(ui_SettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsButton, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsButton, lv_color_hex(0x0069BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingsButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SettingsButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SettingsButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButtonLabel = lv_label_create(ui_SettingsButton);
    lv_obj_set_width(ui_SettingsButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsButtonLabel, "SETTINGS");
    lv_obj_set_style_text_font(ui_SettingsButtonLabel, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FrequencyContainer = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_FrequencyContainer);
    lv_obj_set_width(ui_FrequencyContainer, 120);
    lv_obj_set_height(ui_FrequencyContainer, 252);
    lv_obj_set_x(ui_FrequencyContainer, 81);
    lv_obj_set_y(ui_FrequencyContainer, -113);
    lv_obj_set_align(ui_FrequencyContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FrequencyContainer, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_FrequencyContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FrequencyContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_FrequencyContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FrequencyContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FrequencyContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FrequencyContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_FrequencyContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_FrequencyContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FrequencyButton = lv_btn_create(ui_FrequencyContainer);
    lv_obj_set_width(ui_FrequencyButton, lv_pct(80));
    lv_obj_set_height(ui_FrequencyButton, lv_pct(15));
    lv_obj_set_x(ui_FrequencyButton, -11);
    lv_obj_set_y(ui_FrequencyButton, 99);
    lv_obj_set_align(ui_FrequencyButton, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_FrequencyButton, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_FrequencyButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FrequencyButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FrequencyButton, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_FrequencyButton, 6, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_FrequencyButton, lv_color_hex(0x140282), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_FrequencyButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_FrequencyButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_FrequencyButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_FrequencyButton, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_FrequencyButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_FrequencyButton, 12, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_FrequencyButton, 9, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_FrequencyTitle = lv_label_create(ui_FrequencyButton);
    lv_obj_set_width(ui_FrequencyTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FrequencyTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FrequencyTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FrequencyTitle, "speed");
    lv_obj_set_style_text_font(ui_FrequencyTitle, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FrequencySlider = lv_slider_create(ui_FrequencyContainer);
    lv_slider_set_range(ui_FrequencySlider, 1, 30);
    lv_slider_set_value(ui_FrequencySlider, 25, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_FrequencySlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_FrequencySlider, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_FrequencySlider, lv_pct(35));
    lv_obj_set_flex_grow(ui_FrequencySlider, 1);
    lv_obj_set_x(ui_FrequencySlider, -397);
    lv_obj_set_y(ui_FrequencySlider, -238);
    lv_obj_set_align(ui_FrequencySlider, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FrequencySlider, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FrequencySlider, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_FrequencySlider, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_FrequencySlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_FrequencySlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_FrequencySlider, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_FrequencySlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_FrequencySlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FrequencySlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FrequencySlider, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FrequencySlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_FrequencySlider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_FrequencySlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_FrequencySlider, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FrequencySlider, lv_color_hex(0x052082), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FrequencySlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_FrequencySlider, lv_color_hex(0x2095F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_FrequencySlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_FrequencySlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_FrequencySlider, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_FrequencySlider, 7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_FrequencySlider, lv_color_hex(0x3AFF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_FrequencySlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_FrequencySlider, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_FrequencySlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_FrequencySlider, 20, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FrequencySlider, 20, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FrequencySlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FrequencySlider, -20, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_FrequencyLabel = lv_label_create(ui_FrequencyContainer);
    lv_obj_set_width(ui_FrequencyLabel, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_FrequencyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FrequencyLabel, -416);
    lv_obj_set_y(ui_FrequencyLabel, -274);
    lv_obj_set_align(ui_FrequencyLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_FrequencyLabel, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_FrequencyLabel, "10");
    lv_label_set_recolor(ui_FrequencyLabel, "true");
    lv_obj_set_scroll_dir(ui_FrequencyLabel, LV_DIR_VER);
    lv_obj_set_scroll_snap_x(ui_FrequencyLabel, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_FrequencyLabel, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_text_color(ui_FrequencyLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FrequencyLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FrequencyLabel, &ui_font_Archimoto_Numbers, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerContainer = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_PowerContainer);
    lv_obj_set_width(ui_PowerContainer, 120);
    lv_obj_set_height(ui_PowerContainer, 252);
    lv_obj_set_x(ui_PowerContainer, -98);
    lv_obj_set_y(ui_PowerContainer, -113);
    lv_obj_set_align(ui_PowerContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PowerContainer, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_PowerContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PowerContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PowerContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PowerContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PowerContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PowerContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PowerContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PowerContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerButton = lv_btn_create(ui_PowerContainer);
    lv_obj_set_width(ui_PowerButton, lv_pct(80));
    lv_obj_set_height(ui_PowerButton, lv_pct(15));
    lv_obj_set_x(ui_PowerButton, -11);
    lv_obj_set_y(ui_PowerButton, 99);
    lv_obj_set_align(ui_PowerButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PowerButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PowerButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PowerButton, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PowerButton, 6, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_PowerButton, lv_color_hex(0x140282), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PowerButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_PowerButton, lv_color_hex(0x005297), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_PowerButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_PowerButton, 3, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_PowerButton, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_PowerButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_PowerButton, 12, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_PowerButton, 9, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PowerTitle = lv_label_create(ui_PowerButton);
    lv_obj_set_width(ui_PowerTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerTitle, "power");
    lv_obj_set_style_text_font(ui_PowerTitle, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PowerTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_PowerTitle, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PowerSlider = lv_slider_create(ui_PowerContainer);
    lv_slider_set_range(ui_PowerSlider, 10, 100);
    lv_slider_set_value(ui_PowerSlider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_PowerSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_PowerSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_PowerSlider, lv_pct(35));
    lv_obj_set_flex_grow(ui_PowerSlider, 1);
    lv_obj_set_x(ui_PowerSlider, -158);
    lv_obj_set_y(ui_PowerSlider, -106);
    lv_obj_set_align(ui_PowerSlider, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PowerSlider, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PowerSlider, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_radius(ui_PowerSlider, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PowerSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PowerSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PowerSlider, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PowerSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PowerSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PowerSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PowerSlider, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PowerSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_PowerSlider, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PowerSlider, lv_color_hex(0x052082), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PowerSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PowerSlider, lv_color_hex(0x2095F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PowerSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PowerSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PowerSlider, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_PowerSlider, 7, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PowerSlider, lv_color_hex(0x3AFF00), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PowerSlider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PowerSlider, 4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PowerSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PowerSlider, 20, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PowerSlider, 20, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PowerSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PowerSlider, -20, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PowerLabel = lv_label_create(ui_PowerContainer);
    lv_obj_set_width(ui_PowerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PowerLabel, -163);
    lv_obj_set_y(ui_PowerLabel, -274);
    lv_obj_set_align(ui_PowerLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PowerLabel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PowerLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_long_mode(ui_PowerLabel, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_PowerLabel, "10");
    lv_label_set_recolor(ui_PowerLabel, "true");
    lv_obj_set_scroll_dir(ui_PowerLabel, LV_DIR_VER);
    lv_obj_set_scroll_snap_x(ui_PowerLabel, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_scroll_snap_y(ui_PowerLabel, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_text_color(ui_PowerLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PowerLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PowerLabel, &ui_font_Archimoto_Numbers, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SoftBtn, ui_event_SoftBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MediumBtn, ui_event_MediumBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HardBtn, ui_event_HardBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CustomBtn, ui_event_CustomBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsButton, ui_event_SettingsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FrequencyButton, ui_event_FrequencyButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FrequencySlider, ui_event_FrequencySlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PowerButton, ui_event_PowerButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PowerSlider, ui_event_PowerSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_PresetsButtonContainer = NULL;
    ui_SoftBtn = NULL;
    ui_SoftLabel = NULL;
    ui_MediumBtn = NULL;
    ui_MediumLabel = NULL;
    ui_HardBtn = NULL;
    ui_HardLabel = NULL;
    ui_CustomBtn = NULL;
    ui_CustomLabel = NULL;
    ui_Container4 = NULL;
    ui_PedalLabel = NULL;
    ui_PedalBar = NULL;
    ui_SettingsButton = NULL;
    ui_SettingsButtonLabel = NULL;
    ui_FrequencyContainer = NULL;
    ui_FrequencyButton = NULL;
    ui_FrequencyTitle = NULL;
    ui_FrequencySlider = NULL;
    ui_FrequencyLabel = NULL;
    ui_PowerContainer = NULL;
    ui_PowerButton = NULL;
    ui_PowerTitle = NULL;
    ui_PowerSlider = NULL;
    ui_PowerLabel = NULL;

}
