// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: VoltSet

#include "ui.h"

lv_obj_t * ui_StartupScreen = NULL;
lv_obj_t * ui_LabelSlogan = NULL;
lv_obj_t * ui_LabelVoltset = NULL;
lv_obj_t * ui_LoadingSpinner = NULL;
lv_obj_t * ui_LoadingLabel = NULL;
lv_obj_t * ui_LogoImage = NULL;
// event funtions
void ui_event_StartupScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 2000, &ui_MainScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        StartupLoadValues(e);
    }
}

// build funtions

void ui_StartupScreen_screen_init(void)
{
    ui_StartupScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StartupScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StartupScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartupScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSlogan = lv_label_create(ui_StartupScreen);
    lv_obj_set_width(ui_LabelSlogan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSlogan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSlogan, 0);
    lv_obj_set_y(ui_LabelSlogan, 94);
    lv_obj_set_align(ui_LabelSlogan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSlogan, "powered for perfection");
    lv_obj_set_style_text_color(ui_LabelSlogan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSlogan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSlogan, &ui_font_Archimoto_Labels, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVoltset = lv_label_create(ui_StartupScreen);
    lv_obj_set_width(ui_LabelVoltset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVoltset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelVoltset, 0);
    lv_obj_set_y(ui_LabelVoltset, 57);
    lv_obj_set_align(ui_LabelVoltset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelVoltset, "voltset");
    lv_obj_set_style_text_color(ui_LabelVoltset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVoltset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVoltset, &ui_font_Archimoto_Numbers, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoadingSpinner = lv_spinner_create(ui_StartupScreen, 1000, 90);
    lv_obj_set_width(ui_LoadingSpinner, 55);
    lv_obj_set_height(ui_LoadingSpinner, 55);
    lv_obj_set_x(ui_LoadingSpinner, 0);
    lv_obj_set_y(ui_LoadingSpinner, 158);
    lv_obj_set_align(ui_LoadingSpinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LoadingSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_LoadingSpinner, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_LoadingSpinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_LoadingSpinner, lv_color_hex(0x2095F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_LoadingSpinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_LoadingSpinner, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LoadingLabel = lv_label_create(ui_StartupScreen);
    lv_obj_set_width(ui_LoadingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoadingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoadingLabel, 0);
    lv_obj_set_y(ui_LoadingLabel, 209);
    lv_obj_set_align(ui_LoadingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoadingLabel, "Loading config");
    lv_obj_set_style_text_color(ui_LoadingLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoadingLabel, &ui_font_Archimoto_Labels, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoImage = lv_img_create(ui_StartupScreen);
    lv_img_set_src(ui_LogoImage, &ui_img_logopng_png);
    lv_obj_set_width(ui_LogoImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LogoImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LogoImage, 0);
    lv_obj_set_y(ui_LogoImage, -107);
    lv_obj_set_align(ui_LogoImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LogoImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LogoImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_LogoImage, 200);

    lv_obj_add_event_cb(ui_StartupScreen, ui_event_StartupScreen, LV_EVENT_ALL, NULL);

}

void ui_StartupScreen_screen_destroy(void)
{
    if(ui_StartupScreen) lv_obj_del(ui_StartupScreen);

    // NULL screen variables
    ui_StartupScreen = NULL;
    ui_LabelSlogan = NULL;
    ui_LabelVoltset = NULL;
    ui_LoadingSpinner = NULL;
    ui_LoadingLabel = NULL;
    ui_LogoImage = NULL;

}
