// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: VoltSet

#ifndef UI_STARTUPSCREEN_H
#define UI_STARTUPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_StartupScreen
extern void ui_StartupScreen_screen_init(void);
extern void ui_StartupScreen_screen_destroy(void);
extern void ui_event_StartupScreen(lv_event_t * e);
extern lv_obj_t * ui_StartupScreen;
extern lv_obj_t * ui_LabelSlogan;
extern lv_obj_t * ui_LabelVoltset;
extern lv_obj_t * ui_LoadingSpinner;
extern lv_obj_t * ui_LoadingLabel;
extern lv_obj_t * ui_LogoImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

