// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: VoltSet

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern void ui_event_SettingsScreen(lv_event_t * e);
extern lv_obj_t * ui_SettingsScreen;
extern void ui_event_ZeroInfoButton(lv_event_t * e);
extern lv_obj_t * ui_ZeroInfoButton;
extern lv_obj_t * ui_ZeroInfoLabel;
extern void ui_event_SetUpButton(lv_event_t * e);
extern lv_obj_t * ui_SetUpButton;
extern lv_obj_t * ui_SetupButtonLabel;
extern void ui_event_BackButton(lv_event_t * e);
extern lv_obj_t * ui_BackButton;
extern lv_obj_t * ui_BackButtonLabel;
extern void ui_event_InfoPanel(lv_event_t * e);
extern lv_obj_t * ui_InfoPanel;
extern lv_obj_t * ui_InfoLabel;
extern lv_obj_t * ui_ContainerAll;
extern lv_obj_t * ui_InputContainer;
extern lv_obj_t * ui_SetupVoltage;
extern void ui_event_InputVoltageInfoButton(lv_event_t * e);
extern lv_obj_t * ui_InputVoltageInfoButton;
extern lv_obj_t * ui_InputVoltageInfoLabel;
extern void ui_event_InputVoltageSlider(lv_event_t * e);
extern lv_obj_t * ui_InputVoltageSlider;
extern lv_obj_t * ui_InputVoltageLabel;
extern lv_obj_t * ui_VoltageContainer;
extern lv_obj_t * ui_SolenoidVoltage;
extern void ui_event_SolenoidVoltageInfoButton(lv_event_t * e);
extern lv_obj_t * ui_SolenoidVoltageInfoButton;
extern lv_obj_t * ui_SolenoidVoltageInfoLabel;
extern void ui_event_SolenoidVoltageSlider(lv_event_t * e);
extern lv_obj_t * ui_SolenoidVoltageSlider;
extern lv_obj_t * ui_SolenoidVoltageLabel;
extern lv_obj_t * ui_PulseContainer;
extern lv_obj_t * ui_SolenoidPulseTime;
extern void ui_event_SolenoidPulseInfoButton(lv_event_t * e);
extern lv_obj_t * ui_SolenoidPulseInfoButton;
extern lv_obj_t * ui_SolenoidPulseInfoLabel;
extern void ui_event_SolenoidPulseSlider(lv_event_t * e);
extern lv_obj_t * ui_SolenoidPulseSlider;
extern lv_obj_t * ui_SolenoidPulseLabel;
extern void ui_event_ZeroButton(lv_event_t * e);
extern lv_obj_t * ui_ZeroButton;
extern lv_obj_t * ui_BackButtonLabel1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

