// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: VoltSet

#include "ui.h"

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_ZeroInfoButton = NULL;
lv_obj_t * ui_ZeroInfoLabel = NULL;
lv_obj_t * ui_SetUpButton = NULL;
lv_obj_t * ui_SetupButtonLabel = NULL;
lv_obj_t * ui_BackButton = NULL;
lv_obj_t * ui_BackButtonLabel = NULL;
lv_obj_t * ui_InfoPanel = NULL;
lv_obj_t * ui_InfoLabel = NULL;
lv_obj_t * ui_ContainerAll = NULL;
lv_obj_t * ui_InputContainer = NULL;
lv_obj_t * ui_SetupVoltage = NULL;
lv_obj_t * ui_InputVoltageInfoButton = NULL;
lv_obj_t * ui_InputVoltageInfoLabel = NULL;
lv_obj_t * ui_InputVoltageSlider = NULL;
lv_obj_t * ui_InputVoltageLabel = NULL;
lv_obj_t * ui_VoltageContainer = NULL;
lv_obj_t * ui_SolenoidVoltage = NULL;
lv_obj_t * ui_SolenoidVoltageInfoButton = NULL;
lv_obj_t * ui_SolenoidVoltageInfoLabel = NULL;
lv_obj_t * ui_SolenoidVoltageSlider = NULL;
lv_obj_t * ui_SolenoidVoltageLabel = NULL;
lv_obj_t * ui_PulseContainer = NULL;
lv_obj_t * ui_SolenoidPulseTime = NULL;
lv_obj_t * ui_SolenoidPulseInfoButton = NULL;
lv_obj_t * ui_SolenoidPulseInfoLabel = NULL;
lv_obj_t * ui_SolenoidPulseSlider = NULL;
lv_obj_t * ui_SolenoidPulseLabel = NULL;
lv_obj_t * ui_ZeroButton = NULL;
lv_obj_t * ui_BackButtonLabel1 = NULL;
// event funtions
void ui_event_SettingsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        SettingsLoadValues(e);
    }
}

void ui_event_ZeroInfoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_checked_set_text_value(ui_InfoLabel, target, "",
                                   "This button sets the zero value of your pedal for pedals that have residual internal resistance. Release the pedal or set it to minimum during the procedure.");
    }
}

void ui_event_SetUpButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_SolenoidPulseSlider, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_TOGGLE);
        _ui_state_modify(ui_SetUpButton, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        _ui_checked_set_text_value(ui_InfoLabel, target,
                                   "Change the pulse time to maximum, then, go down to the minimum value where the impact is still strong.",
                                   "go back to save your configuration. This setup is only done once.");
        SaveSetupValue(e);
        _ui_flag_modify(ui_SolenoidVoltageSlider, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_InputVoltageSlider, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_BackButton, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_ZeroButton, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_OUT_RIGHT, 500, 0, &ui_MainScreen_screen_init);
    }
}

void ui_event_InfoPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_checked_set_text_value(ui_InfoLabel, target, "",
                                   "Crafted with care, coded with hope, built for beauty. You are loved. You are capable. Keep going.");
    }
}

void ui_event_InputVoltageInfoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_checked_set_text_value(ui_InfoLabel, target, "",
                                   "This is the input voltage of the power supply used. It should be below 25 V but no less than 12 volts.");
    }
}

void ui_event_InputVoltageSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_InputVoltageLabel, target, "", "");
        SaveSetupValue(e);
    }
}

void ui_event_SolenoidVoltageInfoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_checked_set_text_value(ui_InfoLabel, target, "",
                                   "If you solenoid is continuous put the voltage x1.8. \nIf intermitent, put the nominal voltage.");
    }
}

void ui_event_SolenoidVoltageSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SolenoidVoltageLabel, target, "", "");
        SaveSetupValue(e);
    }
}

void ui_event_SolenoidPulseInfoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_checked_set_text_value(ui_InfoLabel, target, "", "The pulse time can be set up on the button below.");
    }
}

void ui_event_SolenoidPulseSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_SolenoidPulseLabel, target, "", "");
    }
}

void ui_event_ZeroButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        ZeroPedal(e);
        Zeroing_Animation(ui_ZeroButton, 2);
        _ui_checked_set_text_value(ui_InfoLabel, target, "",
                                   "The pedal zero value has been saved, you do not need to perform this action again for this pedal.");
    }
}

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_SettingsScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED,
                        ui_SettingsScreen_screen_destroy);
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ZeroInfoButton = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_ZeroInfoButton, 27);
    lv_obj_set_height(ui_ZeroInfoButton, 27);
    lv_obj_set_x(ui_ZeroInfoButton, -183);
    lv_obj_set_y(ui_ZeroInfoButton, 372);
    lv_obj_set_align(ui_ZeroInfoButton, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ZeroInfoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ZeroInfoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ZeroInfoButton, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ZeroInfoButton, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ZeroInfoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ZeroInfoButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ZeroInfoButton, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ZeroInfoLabel = lv_label_create(ui_ZeroInfoButton);
    lv_obj_set_width(ui_ZeroInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ZeroInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ZeroInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ZeroInfoLabel, "?");
    lv_obj_set_style_text_font(ui_ZeroInfoLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetUpButton = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_SetUpButton, 158);
    lv_obj_set_height(ui_SetUpButton, 82);
    lv_obj_set_x(ui_SetUpButton, 76);
    lv_obj_set_y(ui_SetUpButton, 194);
    lv_obj_set_align(ui_SetUpButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetUpButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SetUpButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SetUpButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SetUpButton, lv_color_hex(0x0069BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetUpButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SetUpButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SetUpButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SetUpButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SetUpButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SetUpButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SetUpButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SetUpButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetupButtonLabel = lv_label_create(ui_SetUpButton);
    lv_obj_set_width(ui_SetupButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetupButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetupButtonLabel, -1);
    lv_obj_set_y(ui_SetupButtonLabel, 0);
    lv_obj_set_align(ui_SetupButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetupButtonLabel, "Hold to\nSet Up");
    lv_obj_set_style_text_align(ui_SetupButtonLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetupButtonLabel, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButton = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_BackButton, 91);
    lv_obj_set_height(ui_BackButton, 58);
    lv_obj_set_x(ui_BackButton, -106);
    lv_obj_set_y(ui_BackButton, 204);
    lv_obj_set_align(ui_BackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BackButton, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BackButton, lv_color_hex(0x0069BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BackButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BackButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BackButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtonLabel = lv_label_create(ui_BackButton);
    lv_obj_set_width(ui_BackButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackButtonLabel, "Back");
    lv_obj_set_style_text_font(ui_BackButtonLabel, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoPanel = lv_obj_create(ui_SettingsScreen);
    lv_obj_set_height(ui_InfoPanel, 141);
    lv_obj_set_width(ui_InfoPanel, lv_pct(100));
    lv_obj_set_x(ui_InfoPanel, 2);
    lv_obj_set_y(ui_InfoPanel, 52);
    lv_obj_set_align(ui_InfoPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_InfoPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_InfoPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_InfoPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InfoLabel = lv_label_create(ui_InfoPanel);
    lv_obj_set_width(ui_InfoLabel, lv_pct(100));
    lv_obj_set_height(ui_InfoLabel, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_InfoLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_InfoLabel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_InfoLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_InfoLabel, "info panel");
    lv_obj_set_style_text_font(ui_InfoLabel, &ui_font_Archimoto_Labels, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerAll = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_ContainerAll);
    lv_obj_set_height(ui_ContainerAll, 238);
    lv_obj_set_width(ui_ContainerAll, lv_pct(100));
    lv_obj_set_x(ui_ContainerAll, 0);
    lv_obj_set_y(ui_ContainerAll, -119);
    lv_obj_set_align(ui_ContainerAll, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerAll, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_ContainerAll, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerAll, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InputContainer = lv_obj_create(ui_ContainerAll);
    lv_obj_remove_style_all(ui_InputContainer);
    lv_obj_set_width(ui_InputContainer, lv_pct(100));
    lv_obj_set_height(ui_InputContainer, lv_pct(30));
    lv_obj_set_x(ui_InputContainer, -146);
    lv_obj_set_y(ui_InputContainer, -201);
    lv_obj_set_align(ui_InputContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_InputContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_InputContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_InputContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_InputContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_InputContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_InputContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_InputContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_InputContainer, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_InputContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetupVoltage = lv_label_create(ui_InputContainer);
    lv_obj_set_width(ui_SetupVoltage, lv_pct(88));
    lv_obj_set_height(ui_SetupVoltage, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_SetupVoltage, -199);
    lv_obj_set_y(ui_SetupVoltage, -245);
    lv_obj_set_align(ui_SetupVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetupVoltage, "system input voltage");
    lv_obj_set_style_text_color(ui_SetupVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetupVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetupVoltage, &ui_font_Archimoto_Labels, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputVoltageInfoButton = lv_btn_create(ui_InputContainer);
    lv_obj_set_width(ui_InputVoltageInfoButton, 27);
    lv_obj_set_height(ui_InputVoltageInfoButton, 27);
    lv_obj_set_x(ui_InputVoltageInfoButton, 111);
    lv_obj_set_y(ui_InputVoltageInfoButton, -117);
    lv_obj_set_align(ui_InputVoltageInfoButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InputVoltageInfoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_InputVoltageInfoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_InputVoltageInfoButton, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_InputVoltageInfoButton, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_InputVoltageInfoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_InputVoltageInfoButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InputVoltageInfoButton, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputVoltageInfoLabel = lv_label_create(ui_InputVoltageInfoButton);
    lv_obj_set_width(ui_InputVoltageInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InputVoltageInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_InputVoltageInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InputVoltageInfoLabel, "?");
    lv_obj_set_style_text_font(ui_InputVoltageInfoLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputVoltageSlider = lv_slider_create(ui_InputContainer);
    lv_slider_set_range(ui_InputVoltageSlider, 9, 25);
    lv_slider_set_value(ui_InputVoltageSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_InputVoltageSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_InputVoltageSlider, 0,
                                                                                                       LV_ANIM_OFF);
    lv_obj_set_width(ui_InputVoltageSlider, lv_pct(80));
    lv_obj_set_height(ui_InputVoltageSlider, lv_pct(30));
    lv_obj_set_x(ui_InputVoltageSlider, -196);
    lv_obj_set_y(ui_InputVoltageSlider, -191);
    lv_obj_set_align(ui_InputVoltageSlider, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InputVoltageSlider, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_InputVoltageSlider, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InputVoltageLabel = lv_label_create(ui_InputContainer);
    lv_obj_set_width(ui_InputVoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InputVoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InputVoltageLabel, 128);
    lv_obj_set_y(ui_InputVoltageLabel, -190);
    lv_obj_set_align(ui_InputVoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InputVoltageLabel, "9");
    lv_obj_set_style_text_color(ui_InputVoltageLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_InputVoltageLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_InputVoltageLabel, &ui_font_Archimoto_Numbers, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VoltageContainer = lv_obj_create(ui_ContainerAll);
    lv_obj_remove_style_all(ui_VoltageContainer);
    lv_obj_set_width(ui_VoltageContainer, lv_pct(100));
    lv_obj_set_height(ui_VoltageContainer, lv_pct(30));
    lv_obj_set_x(ui_VoltageContainer, -146);
    lv_obj_set_y(ui_VoltageContainer, -33);
    lv_obj_set_align(ui_VoltageContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VoltageContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_VoltageContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_VoltageContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_VoltageContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VoltageContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VoltageContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VoltageContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_VoltageContainer, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_VoltageContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolenoidVoltage = lv_label_create(ui_VoltageContainer);
    lv_obj_set_width(ui_SolenoidVoltage, lv_pct(88));
    lv_obj_set_height(ui_SolenoidVoltage, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_SolenoidVoltage, -199);
    lv_obj_set_y(ui_SolenoidVoltage, -245);
    lv_obj_set_align(ui_SolenoidVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SolenoidVoltage, "Nominal solenoid Voltage");
    lv_obj_set_style_text_color(ui_SolenoidVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SolenoidVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SolenoidVoltage, &ui_font_Archimoto_Labels, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolenoidVoltageInfoButton = lv_btn_create(ui_VoltageContainer);
    lv_obj_set_width(ui_SolenoidVoltageInfoButton, 27);
    lv_obj_set_height(ui_SolenoidVoltageInfoButton, 27);
    lv_obj_set_x(ui_SolenoidVoltageInfoButton, 111);
    lv_obj_set_y(ui_SolenoidVoltageInfoButton, -117);
    lv_obj_set_align(ui_SolenoidVoltageInfoButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SolenoidVoltageInfoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SolenoidVoltageInfoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SolenoidVoltageInfoButton, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SolenoidVoltageInfoButton, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SolenoidVoltageInfoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SolenoidVoltageInfoButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SolenoidVoltageInfoButton, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolenoidVoltageInfoLabel = lv_label_create(ui_SolenoidVoltageInfoButton);
    lv_obj_set_width(ui_SolenoidVoltageInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SolenoidVoltageInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SolenoidVoltageInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SolenoidVoltageInfoLabel, "?");
    lv_obj_set_style_text_font(ui_SolenoidVoltageInfoLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolenoidVoltageSlider = lv_slider_create(ui_VoltageContainer);
    lv_slider_set_range(ui_SolenoidVoltageSlider, 6, 18);
    lv_slider_set_value(ui_SolenoidVoltageSlider, 6, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SolenoidVoltageSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_SolenoidVoltageSlider, 6, LV_ANIM_OFF);
    lv_obj_set_width(ui_SolenoidVoltageSlider, lv_pct(80));
    lv_obj_set_height(ui_SolenoidVoltageSlider, lv_pct(30));
    lv_obj_set_x(ui_SolenoidVoltageSlider, -196);
    lv_obj_set_y(ui_SolenoidVoltageSlider, -191);
    lv_obj_set_align(ui_SolenoidVoltageSlider, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SolenoidVoltageSlider, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SolenoidVoltageSlider, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolenoidVoltageLabel = lv_label_create(ui_VoltageContainer);
    lv_obj_set_width(ui_SolenoidVoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SolenoidVoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SolenoidVoltageLabel, 128);
    lv_obj_set_y(ui_SolenoidVoltageLabel, -190);
    lv_obj_set_align(ui_SolenoidVoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SolenoidVoltageLabel, "6");
    lv_obj_set_style_text_color(ui_SolenoidVoltageLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SolenoidVoltageLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SolenoidVoltageLabel, &ui_font_Archimoto_Numbers, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PulseContainer = lv_obj_create(ui_ContainerAll);
    lv_obj_remove_style_all(ui_PulseContainer);
    lv_obj_set_width(ui_PulseContainer, lv_pct(100));
    lv_obj_set_height(ui_PulseContainer, lv_pct(30));
    lv_obj_set_x(ui_PulseContainer, -146);
    lv_obj_set_y(ui_PulseContainer, 91);
    lv_obj_set_align(ui_PulseContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PulseContainer, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_PulseContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PulseContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PulseContainer, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PulseContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PulseContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PulseContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PulseContainer, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PulseContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolenoidPulseTime = lv_label_create(ui_PulseContainer);
    lv_obj_set_width(ui_SolenoidPulseTime, lv_pct(88));
    lv_obj_set_height(ui_SolenoidPulseTime, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_SolenoidPulseTime, -199);
    lv_obj_set_y(ui_SolenoidPulseTime, -245);
    lv_obj_set_align(ui_SolenoidPulseTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SolenoidPulseTime, "Handpiece max pulse time");
    lv_obj_set_style_text_color(ui_SolenoidPulseTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SolenoidPulseTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SolenoidPulseTime, &ui_font_Archimoto_Labels, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolenoidPulseInfoButton = lv_btn_create(ui_PulseContainer);
    lv_obj_set_width(ui_SolenoidPulseInfoButton, 27);
    lv_obj_set_height(ui_SolenoidPulseInfoButton, 27);
    lv_obj_set_x(ui_SolenoidPulseInfoButton, 111);
    lv_obj_set_y(ui_SolenoidPulseInfoButton, -117);
    lv_obj_set_align(ui_SolenoidPulseInfoButton, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_SolenoidPulseInfoButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SolenoidPulseInfoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SolenoidPulseInfoButton, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SolenoidPulseInfoButton, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SolenoidPulseInfoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SolenoidPulseInfoButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SolenoidPulseInfoButton, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolenoidPulseInfoLabel = lv_label_create(ui_SolenoidPulseInfoButton);
    lv_obj_set_width(ui_SolenoidPulseInfoLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SolenoidPulseInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SolenoidPulseInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SolenoidPulseInfoLabel, "?");
    lv_obj_set_style_text_font(ui_SolenoidPulseInfoLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolenoidPulseSlider = lv_slider_create(ui_PulseContainer);
    lv_slider_set_range(ui_SolenoidPulseSlider, 1, 25);
    lv_slider_set_value(ui_SolenoidPulseSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SolenoidPulseSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SolenoidPulseSlider,
                                                                                                        0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SolenoidPulseSlider, lv_pct(80));
    lv_obj_set_height(ui_SolenoidPulseSlider, lv_pct(30));
    lv_obj_set_x(ui_SolenoidPulseSlider, -196);
    lv_obj_set_y(ui_SolenoidPulseSlider, -191);
    lv_obj_set_align(ui_SolenoidPulseSlider, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SolenoidPulseSlider, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_SolenoidPulseSlider, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SolenoidPulseLabel = lv_label_create(ui_PulseContainer);
    lv_obj_set_width(ui_SolenoidPulseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SolenoidPulseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SolenoidPulseLabel, 128);
    lv_obj_set_y(ui_SolenoidPulseLabel, -190);
    lv_obj_set_align(ui_SolenoidPulseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SolenoidPulseLabel, "0");
    lv_obj_set_style_text_color(ui_SolenoidPulseLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SolenoidPulseLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SolenoidPulseLabel, &ui_font_Archimoto_Numbers, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ZeroButton = lv_btn_create(ui_SettingsScreen);
    lv_obj_set_width(ui_ZeroButton, 91);
    lv_obj_set_height(ui_ZeroButton, 34);
    lv_obj_set_x(ui_ZeroButton, -106);
    lv_obj_set_y(ui_ZeroButton, 148);
    lv_obj_set_align(ui_ZeroButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ZeroButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ZeroButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ZeroButton, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ZeroButton, lv_color_hex(0x0069BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ZeroButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ZeroButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ZeroButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ZeroButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ZeroButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ZeroButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ZeroButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ZeroButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackButtonLabel1 = lv_label_create(ui_ZeroButton);
    lv_obj_set_width(ui_BackButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BackButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BackButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BackButtonLabel1, "Zero");
    lv_obj_set_style_text_font(ui_BackButtonLabel1, &ui_font_Archimoto_EXTRA, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ZeroInfoButton, ui_event_ZeroInfoButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetUpButton, ui_event_SetUpButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BackButton, ui_event_BackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InfoPanel, ui_event_InfoPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InputVoltageInfoButton, ui_event_InputVoltageInfoButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InputVoltageSlider, ui_event_InputVoltageSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SolenoidVoltageInfoButton, ui_event_SolenoidVoltageInfoButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SolenoidVoltageSlider, ui_event_SolenoidVoltageSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SolenoidPulseInfoButton, ui_event_SolenoidPulseInfoButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SolenoidPulseSlider, ui_event_SolenoidPulseSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ZeroButton, ui_event_ZeroButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsScreen, ui_event_SettingsScreen, LV_EVENT_ALL, NULL);

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_ZeroInfoButton = NULL;
    ui_ZeroInfoLabel = NULL;
    ui_SetUpButton = NULL;
    ui_SetupButtonLabel = NULL;
    ui_BackButton = NULL;
    ui_BackButtonLabel = NULL;
    ui_InfoPanel = NULL;
    ui_InfoLabel = NULL;
    ui_ContainerAll = NULL;
    ui_InputContainer = NULL;
    ui_SetupVoltage = NULL;
    ui_InputVoltageInfoButton = NULL;
    ui_InputVoltageInfoLabel = NULL;
    ui_InputVoltageSlider = NULL;
    ui_InputVoltageLabel = NULL;
    ui_VoltageContainer = NULL;
    ui_SolenoidVoltage = NULL;
    ui_SolenoidVoltageInfoButton = NULL;
    ui_SolenoidVoltageInfoLabel = NULL;
    ui_SolenoidVoltageSlider = NULL;
    ui_SolenoidVoltageLabel = NULL;
    ui_PulseContainer = NULL;
    ui_SolenoidPulseTime = NULL;
    ui_SolenoidPulseInfoButton = NULL;
    ui_SolenoidPulseInfoLabel = NULL;
    ui_SolenoidPulseSlider = NULL;
    ui_SolenoidPulseLabel = NULL;
    ui_ZeroButton = NULL;
    ui_BackButtonLabel1 = NULL;

}
